require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 3.0', '< 4.0'
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
end

target 'NightsNative' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'NightsNativeTests' do
    inherit! :complete
    # Pods for testing
  end
  
  pod 'OneSignal', '>= 3.0.0', '< 4.0'
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
  

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  #  use_flipper!({ 'Flipper' => '0.75.0' })
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
     end
  end
end
