# Generated by Django 3.0.6 on 2020-06-13 05:12

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPromo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('title_ar', models.CharField(max_length=60)),
                ('body', models.CharField(max_length=250)),
                ('body_ar', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='landing_promos')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('released_at', models.CharField(blank=True, default=api.models.get_year, max_length=4)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_api.topic_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Topic')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.topic',),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Topic')),
                ('plot', models.TextField(null=True)),
                ('runtime', models.IntegerField(blank=True, help_text='In minutes', null=True)),
                ('index', models.IntegerField(blank=True, default=0, help_text='Episode number')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.topic',),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Topic')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.topic',),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Topic')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.topic',),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Topic')),
                ('index', models.IntegerField(blank=True, default=0, help_text='Season number')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.topic',),
        ),
        migrations.CreateModel(
            name='ViewHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='title', max_length=10)),
                ('playback_position', models.IntegerField(blank=True, default=0)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('hit_message', models.CharField(blank=True, max_length=100, null=True)),
                ('hit_date', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='api.Topic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewhits', to='api.Episode')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewhits', to='api.Season')),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='watched', through='api.ViewHit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('url', models.TextField()),
                ('formats', models.CharField(max_length=255)),
                ('qualities', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField()),
                ('availability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Availability')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.Media')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Provider')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Provider'),
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Topic')),
                ('plot', models.TextField(null=True)),
                ('runtime', models.IntegerField(blank=True, help_text='In minutes', null=True)),
                ('imdb', models.CharField(max_length=50, null=True)),
                ('rating', models.FloatField(null=True)),
                ('type', models.CharField(choices=[('m', 'Movie'), ('s', 'Series')], default='m', max_length=10)),
                ('rated', models.IntegerField(blank=True, null=True)),
                ('cast', models.ManyToManyField(blank=True, related_name='titles', to='api.Cast')),
                ('genres', models.ManyToManyField(blank=True, related_name='titles', to='api.Genre')),
                ('languages', models.ManyToManyField(blank=True, related_name='titles', to='api.Language')),
                ('users', models.ManyToManyField(blank=True, related_name='my_list', through='api.MyList', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.topic',),
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(limit_choices_to={'type': 's'}, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='api.Title'),
        ),
        migrations.AddField(
            model_name='mylist',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Title'),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='api.Season'),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='api.Title'),
        ),
    ]
