# Generated by Django 3.0.6 on 2020-06-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200613_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
