# Generated by Django 3.0.5 on 2020-04-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200411_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='titles', to='api.Cast'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='titles', to='api.Genre'),
        ),
    ]
