# Generated by Django 3.0.6 on 2020-06-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_title_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='is_slide',
            field=models.BooleanField(default=False),
        ),
    ]
