# Generated by Django 3.0.5 on 2020-04-12 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200412_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Topic')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.topic',),
        ),
        migrations.AddField(
            model_name='title',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='titles', to='api.Language'),
        ),
    ]
