# Generated by Django 3.0.6 on 2020-06-19 05:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_episode_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='episode_series',
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.models.OverwriteStorage(), upload_to='episodes_images'),
        ),
    ]
