# Generated by Django 3.0.5 on 2020-04-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_viewhit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewhit',
            name='type',
            field=models.CharField(blank=True, default='m', max_length=10),
        ),
    ]
