# Generated by Django 3.0.6 on 2020-10-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200619_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='coming_soon_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
