# Generated by Django 3.0.6 on 2020-10-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_title_coming_soon_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='coming_soon_at',
        ),
        migrations.AddField(
            model_name='title',
            name='is_coming_soon',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
