# Generated by Django 3.0.5 on 2020-04-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_episodevideo_image_movievideo_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='qualities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
