# Generated by Django 3.0.5 on 2020-04-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200421_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='content',
            new_name='url',
        ),
    ]
