# Generated by Django 3.0.6 on 2020-05-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200421_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPromo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('body', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='landing_promos')),
            ],
        ),
    ]
