# Generated by Django 3.0.6 on 2020-05-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_landingpromo'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpromo',
            name='body_ar',
            field=models.CharField(default='Test', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landingpromo',
            name='title_ar',
            field=models.CharField(default='Test', max_length=60),
            preserve_default=False,
        ),
    ]
