# Generated by Django 3.0.6 on 2020-06-08 02:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200526_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='released_at',
            field=models.CharField(blank=True, default=api.models.get_year, max_length=4),
        ),
    ]
