# Generated by Django 3.0.6 on 2020-06-08 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200608_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Provider'),
        ),
    ]
