# Generated by Django 3.0.5 on 2020-04-07 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('plot', models.TextField(null=True)),
                ('imdb', models.CharField(max_length=50, null=True)),
                ('rating', models.FloatField(null=True)),
                ('type', models.CharField(choices=[('m', 'Movie'), ('s', 'Series')], default='m', max_length=10)),
                ('rated', models.CharField(choices=[('G', 'G - General Audiences'), ('PG', 'PG - Parental Guidance Suggested'), ('PG-13', 'PG-13 - Parents Strongly Cautioned'), ('R', 'R - Restricted'), ('NC-17', 'NC-17 - Adults Only')], default='G', max_length=10)),
                ('runtime', models.IntegerField(blank=True, help_text='In minutes', null=True)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cast', models.ManyToManyField(blank=True, to='api.Cast')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('index', models.IntegerField(blank=True, default=0, help_text='Season number')),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Title')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('index', models.IntegerField(blank=True, default=0, help_text='Episode number')),
                ('runtime', models.IntegerField(blank=True, help_text='In minutes', null=True)),
                ('plot', models.TextField(null=True)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Season')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Title')),
            ],
        ),
    ]
