# Generated by Django 3.0.5 on 2020-04-10 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_api.topic_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Topic')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.topic',),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Topic')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.topic',),
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Topic')),
                ('plot', models.TextField(null=True)),
                ('runtime', models.IntegerField(blank=True, help_text='In minutes', null=True)),
                ('imdb', models.CharField(max_length=50, null=True)),
                ('rating', models.FloatField(null=True)),
                ('type', models.CharField(choices=[('m', 'Movie'), ('s', 'Series')], default='m', max_length=10)),
                ('rated', models.CharField(choices=[('G', 'G - General Audiences'), ('PG', 'PG - Parental Guidance Suggested'), ('PG-13', 'PG-13 - Parents Strongly Cautioned'), ('R', 'R - Restricted'), ('NC-17', 'NC-17 - Adults Only')], default='G', max_length=10)),
                ('cast', models.ManyToManyField(blank=True, to='api.Cast')),
                ('genres', models.ManyToManyField(blank=True, to='api.Genre')),
                ('users', models.ManyToManyField(blank=True, related_name='my_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.topic',),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Topic')),
                ('index', models.IntegerField(blank=True, default=0, help_text='Season number')),
                ('series', models.ForeignKey(limit_choices_to={'type': 's'}, on_delete=django.db.models.deletion.CASCADE, to='api.Title')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.topic',),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Topic')),
                ('plot', models.TextField(null=True)),
                ('runtime', models.IntegerField(blank=True, help_text='In minutes', null=True)),
                ('index', models.IntegerField(blank=True, default=0, help_text='Episode number')),
                ('episode_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Season')),
                ('episode_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Title')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api.topic',),
        ),
    ]
