# Generated by Django 3.0.5 on 2020-04-11 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewhit',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewhits', to='api.Episode'),
        ),
        migrations.AddField(
            model_name='viewhit',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewhits', to='api.Season'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='api.Season'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='api.Title'),
        ),
        migrations.AlterField(
            model_name='season',
            name='series',
            field=models.ForeignKey(limit_choices_to={'type': 's'}, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='api.Title'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='watched', through='api.ViewHit', to=settings.AUTH_USER_MODEL),
        ),
    ]
