# Generated by Django 3.0.5 on 2020-04-11 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200411_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewhit',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='api.Topic'),
        ),
    ]
