# Generated by Django 3.0.5 on 2020-04-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200412_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewhit',
            name='type',
            field=models.CharField(blank=True, default='title', max_length=10),
        ),
    ]
