# Generated by Django 3.0.5 on 2020-04-21 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200421_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.Topic'),
        ),
    ]
